<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" xml:lang="en" lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>Application Name</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="description" content="" />
<link rel="stylesheet" href="css/styles.css" />
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<span class="navbar-brand">Project name</span>
			</div>

		</div>
	</div>


	<section class="container">
		<div class="panel panel-default">
		  <div class="panel-body">
		  	To install you must first create an empty database.
		  </div>
		</div>
		<?php $this->error = false;?>
		<?php if($this->tmpIsWritable == true) { ?>
			<div class="alert alert-success">MP3 File Directory <i><?php echo $this->fileDir?></i> is writable.</div>
		<?php } else {?>
			<div class="alert alert-danger">MP3 File Directory <i><?php echo $this->fileDir?></i> is not writable. Please fix before continuing.</div>
			<?php $this->error = true?>			
		<?php }?>
	
		<?php  if($this->configIsWritable == true) {?>
			<div class="alert alert-success">Config File <i><?php echo $this->configFile?></i> is writable.</div>
		<?php } else {?>
			<div class="alert alert-danger">Config File <i><?php echo $this->configFile?></i> is not writable.</div>
			<?php $this->error = true?>
		<?php } ?>
		
		<?php if($this->error == false) { ?>
			<?php $this->displayForm = true?>
		<?php } else {?>
			<p>Correct the above errors and Re-Check</p>
			<a href="/install" class="btn btn-primary">Re-Check</a>
		<?php }?>
		
	<?php if($this->displayForm) { ?>
		<form role="form" method="post">
		<div class="panel panel-default">
  			<div class="panel-body">
				<h4 class="text-primary">Database Settings</h4>
				<div class="form-group">
					<label for="exampleInputEmail1">Database Name</label> <input
						type="text" class="form-control" id="database_name" name="database_name" value="music">
				</div>
				<div class="form-group">
					<label for="exampleInputPassword1">Database Host</label> <input
						type="text" class="form-control" id="database_host" name="database_host">
				</div>
				<div class="form-group">
					<label for="exampleInputPassword1">Database User</label> <input
						type="text" class="form-control" id="database_user" name="database_user">
				</div>
				<div class="form-group">
					<label for="exampleInputPassword1">Database Password</label> <input
						type="text" class="form-control" id="database_password" name="database_password">
				</div>
			</div>
			</div>
			
			<div class="panel panel-default">
  			<div class="panel-body">
			<h4 class="text-primary">Default Admin</h4>
			<div class="form-group">
				<label for="exampleInputPassword1">Account Name</label> <input
					type="text" class="form-control" id="account_name" name="account_name">
			</div>
			<div class="form-group">
				<label for="exampleInputPassword1">Account Email</label> <input
					type="text" class="form-control" id="account_email" name="account_email">
			</div>
			<div class="form-group">
				<label for="exampleInputPassword1">Account Password</label> <input
					type="text" class="form-control" id="account_password" name="account_password">
			</div>
			</div></div>
			<button type="submit" class="btn btn-default">Save</button>
		</form>
	<?php }?>
		
	</section>
	<section id="footer">
		<div class="footer">
			<div class="container">
				<p class="text-muted">Place sticky footer content here.</p>
			</div>
		</div>
	</section>
</body>
</html>
